### ISSUE TITLE
Timeout error while pyodbc.connect

### ISSUE THREAD

**Issue by SezzR** [matt-bertoncello/python-pyodbc-buildpack#1]
Hi,
I have get a timeout connection error for three days. Before 3 days ago, I can connect to SQL Server driver successfuly. What may be the problem?
My connection command is this:

self.conn = pyodbc.connect("DRIVER={ODBC Driver 17 for SQL Server};SERVER=mssql09.trwww.com;DATABASE=aaa;UID=bbb;PWD=xxx")
            
Problem is this:
 ('HYT00', '[HYT00] [unixODBC][Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
Thanks

**Comment by matt-bertoncello** [comment]
Hi SezzR,

Some online resouces as asked by [jarlh](https://stackoverflow.com/questions/54069846/pyodbc-operationalerror-hyt00-uhyt00-unixodbcmicrosoftodbc-driver-1) and [Krishnang K Dalal](https://stackoverflow.com/questions/50046158/pyodbc-login-timeout-error) indicate this is an issue with the SERVER component of your connection string. Try and add the PORT after the server string separated by a comma, such as:
`self.conn = pyodbc.connect("DRIVER={ODBC Driver 17 for SQL Server};SERVER=mssql09.trwww.com,1433;DATABASE=aaa;UID=bbb;PWD=xxx")`

Have you managed to run this connection string successfully in local before attempting to run it in Heroku?

Thanks
